interface TranslationMap {
  [key: string]: string;
}

const translations: TranslationMap = {
  // Startup & Demo Day terms
  'creating': 'تخلیق کرنا',
  'effective': 'موثر',
  'demo': 'ڈیمو',
  'day': 'دن',
  'presentation': 'پیشکش',
  'has': 'ہے',
  'become': 'بن چکا ہے',
  'an': 'ایک',
  'important': 'اہم',
  'part': 'حصہ',
  'of': 'کا',
  'participating': 'شرکت کرنا',
  'in': 'میں',
  'yc': 'وائی سی',
  'not': 'نہیں',
  'just': 'صرف',
  'due': 'وجہ سے',
  'to': 'کو',
  'the': 'دی',
  'but': 'لیکن',
  'because': 'کیونکہ',
  'very': 'بہت',
  'process': 'عمل',
  'fashioning': 'تیار کرنا',
  'valuable': 'قابل قدر',
  'best': 'بہترین',
  'technique': 'طریقہ',
  'achieve': 'حاصل کرنا',
  'these': 'یہ',
  'qualities': 'خصوصیات',
  'is': 'ہے',
  'repetition': 'تکرار',
  'critique': 'تنقید',
  'and': 'اور',
  'editing': 'ترمیم',
  'including': 'بشمول',
  'importantly': 'اہم طور پر',
  'selective': 'منتخب',
  'removal': 'ہٹانا',
  'vertebrae': 'ریڑھ کی ہڈی',
  'most': 'زیادہ تر',
  'listeners': 'سننے والے',
  'will': 'کریں گے',
  'remember': 'یاد رکھنا',
  'at': 'پر',
  '3': 'تین',
  'or': 'یا',
  '4': 'چار',
  'key': 'اہم',
  'points': 'نکات',
  'from': 'سے',
  'they': 'وہ',
  'heard': 'سنا',
  'especially': 'خاص طور پر',
  'if': 'اگر',
  'it': 'یہ',
  'many': 'کئی',
  'with': 'کے ساتھ',
  'each': 'ہر ایک',
  'one': 'ایک',
  'you': 'آپ',
  'we': 'ہم',
  'sat': 'بیٹھے',
  'down': 'نیچے',
  'figured': 'سمجھا',
  'out': 'باہر',
  '5': 'پانچ',
  '7': 'سات',
  'ideas': 'خیالات',
  'people': 'لوگ',
  'should': 'چاہیے',
  'know': 'جاننا',
  'about': 'کے بارے میں',
  'your': 'آپ کا',
  'startup': 'اسٹارٹ اپ',
  'result': 'نتیجہ',
  'slide': 'سلائیڈ',
  'that': 'جو',
  'no': 'نہیں',
  'can': 'سکتا',
  'easily': 'آسانی سے',
  'without': 'کے بغیر',
  'caption': 'کیپشن',
  'you’d': 'آپ کو',
  'have': 'ہونا',
  'study': 'مطالعہ کرنا',
  'graph': 'گراف',
  'get': 'پانا',
  'conclusion': 'نتیجہ',

  // Business & software
  'software': 'سافٹ ویئر',
  'platform': 'پلیٹ فارم',
  'application': 'ایپلیکیشن',
  'product': 'پروڈکٹ',
  'design': 'ڈیزائن',
  'solution': 'حل',

  // General
  'team': 'ٹیم',
  'growth': 'ترقی',
  'future': 'مستقبل',
  'success': 'کامیابی',
  'guide': 'رہنما',
  'advice': 'مشورہ',
  'build': 'تعمیر کرنا',
  'launch': 'آغاز',
   'list': 'فہرست',
  'what': 'کیا',
  'michael': 'مائیکل',
  'accomplished': 'حاصل کیا',
  'for': 'کے لیے',
  'miles': 'میل',
  'long': 'طویل',
  'something': 'کچھ',
  'likely': 'امکاناً',
  'played': 'ادا کیا',
  'today': 'آج',
  'we’re': 'ہم',
  'kicking': 'آغاز کرنا',
  'off': 'شروع',
  'combinator’s': 'کمبینیٹر کا',
  '38th': 'اڑتیسواں',
  'celebrating': 'جشن منانا',
  'incredible': 'ناقابل یقین',
  'batch': 'بیچ',
  'w24': 'ڈبلیو 24',
  'marks': 'نشاندہی کرتا ہے',
  'completion': 'تکمیل',
  'my': 'میرا',
  'first': 'پہلا',
  'year': 'سال',
  'as': 'بطور',
  'president': 'صدر',
  'amazing': 'شاندار',
  'been': 'رہا ہے',
  
  'results': 'نتائج',
  'was': 'تھا',
  'able': 'قابل',
  'generate': 'بنایا / پیدا کیا',
  'a': 'ایک',
  'schedule': 'شیڈول / نظام الاوقات',
  'over': 'زیادہ',
  '1300': '۱۳۰۰',
  'meetings': 'ملاقاتیں',
  'main': 'اہم',
  'difference': 'فرق',
  'investor': 'سرمایہ کار',
  'scheduling': 'شیڈولنگ',
  'problem': 'مسئلہ',
    'so': 'اس لیے',
  'matches': 'مقابلے / ملاپ',
  'single': 'واحد',
  'run': 'چلانا / بار',
  'algorithm': 'الگورتھم',
  'there': 'وہاں',
  'are': 'ہیں',
  'guarantees': 'ضمانتیں',
  'optimal': 'بہترین / مثالی'

};

export const translateToUrdu = (text: string): string => {
  if (!text || text.trim().length === 0) {
    return '';
  }

  let translated = text;

  // Replace English terms with Urdu equivalents
  Object.entries(translations).forEach(([english, urdu]) => {
    const regex = new RegExp(`\\b${english}\\b`, 'gi'); // Word-boundary aware
    translated = translated.replace(regex, urdu);
  });

  return translated;
};
